services:
  translator:
    image: ghcr.io/cup1dstunt/kinyarwanda-translate:latest
    pull_policy: always
    container_name: uebersetzer-pwa
    env_file: .env
    ports:
      - "8085:8000"
    restart: unless-stopped
